### ISSUE TITLE
Beautify Python string formatting where applicable

### ISSUE THREAD

**Issue by tangaw** [dongskyler/Camera-Search-Trends#25]
A select few of the existing Python functions could use some simplifying/beautifying for better readability.

The solution I have in mind would be to use `%s` and `%d` instead of chaining strings and dashes using plus symbols.

Examples such as the one below could use some retouching:
![String formatting](https://user-images.githubusercontent.com/44086040/80665469-6d0ef380-8a4e-11ea-814e-89d0e5cf775b.PNG)

**Comment by dongskyler** [comment]
https://medium.com/better-programming/four-ways-to-print-variables-in-strings-28b346998d22

https://realpython.com/python-f-strings/

.format() is a good method
